In [1]:
# Update sklearn to prevent version mismatches
!pip install sklearn --upgrade

Collecting sklearn
  Using cached sklearn-0.0.tar.gz (1.1 kB)
Requirement already satisfied, skipping upgrade: scikit-learn in /Users/nicolebroussard/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages (from sklearn) (0.23.1)
Requirement already satisfied, skipping upgrade: numpy>=1.13.3 in /Users/nicolebroussard/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages (from scikit-learn->sklearn) (1.17.0)
Requirement already satisfied, skipping upgrade: threadpoolctl>=2.0.0 in /Users/nicolebroussard/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages (from scikit-learn->sklearn) (2.1.0)
Requirement already satisfied, skipping upgrade: joblib>=0.11 in /Users/nicolebroussard/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages (from scikit-learn->sklearn) (0.16.0)
Requirement already satisfied, skipping upgrade: scipy>=0.19.1 in /Users/nicolebroussard/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages (from scikit-learn->sklearn) (1.5.0)
Building wheels for collected packages: sklearn
  Building wheel for sklearn (setup.py) ... done
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1315 sha256=249a0cc87bd3420ecd80da8c76a0ded381cc23c01fa92989ffca5c2d98e6710c
  Stored in directory: /Users/nicolebroussard/Library/Caches/pip/wheels/23/9d/42/5ec745cbbb17517000a53cecc49d6a865450d1f5cb16dc8a9c
Successfully built sklearn
Installing collected packages: sklearn
Successfully installed sklearn-0.0

In [2]:
# install joblib
!pip install joblib

Requirement already satisfied: joblib in /Users/nicolebroussard/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages (0.16.0)

In [3]:
#Import Dependencies
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("data/coffee_data_cleaned.csv")
df

,Unnamed: 0,index,total_cup_points,species,owner,country_of_origin,farm_name,lot_number,mill,ico_number,...,category_two_defects,expiration,certification_body,certification_address,certification_contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters,length
0,0,0,90.58,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,...,0,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0,4
1,1,1,89.92,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,...,1,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0,4
2,2,3,89.00,Arabica,yidnekachew dabessa,Ethiopia,yidnekachew dabessa coffee plantation,NaN,wolensu,NaN,...,2,"March 25th, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1800.0,2200.0,2000.0,4
3,3,4,88.83,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,...,2,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0,4
4,4,5,88.83,Arabica,ji-ae ahn,Brazil,NaN,NaN,NaN,NaN,...,1,"September 3rd, 2014",Specialty Coffee Institute of Asia,726e4891cf2c9a4848768bd34b668124d12c4224,b70da261fcc84831e3e9620c30a8701540abc200,m,NaN,NaN,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1124,1124,1334,78.75,Robusta,luis robles,Ecuador,robustasa,Lavado 1,our own lab,NaN,...,1,"January 18th, 2017",Specialty Coffee Association,ff7c18ad303d4b603ac3f8cff7e611ffc735e720,352d0cf7f3e9be14dad7df644ad65efc27605ae2,m,NaN,NaN,NaN,4
1125,1125,1335,78.08,Robusta,luis robles,Ecuador,robustasa,Lavado 3,own laboratory,NaN,...,0,"January 18th, 2017",Specialty Coffee Association,ff7c18ad303d4b603ac3f8cff7e611ffc735e720,352d0cf7f3e9be14dad7df644ad65efc27605ae2,m,40.0,40.0,40.0,4
1126,1126,1336,77.17,Robusta,james moore,United States,fazenda cazengo,NaN,cafe cazengo,NaN,...,6,"December 23rd, 2015",Specialty Coffee Association,ff7c18ad303d4b603ac3f8cff7e611ffc735e720,352d0cf7f3e9be14dad7df644ad65efc27605ae2,m,795.0,795.0,795.0,4
1127,1127,1337,75.08,Robusta,cafe politico,India,NaN,NaN,NaN,14-1118-2014-0087,...,1,"August 25th, 2015",Specialty Coffee Association,ff7c18ad303d4b603ac3f8cff7e611ffc735e720,352d0cf7f3e9be14dad7df644ad65efc27605ae2,m,NaN,NaN,NaN,4
1128,1128,1338,73.75,Robusta,cafe politico,Vietnam,NaN,NaN,NaN,NaN,...,9,"August 25th, 2015",Specialty Coffee Association,ff7c18ad303d4b603ac3f8cff7e611ffc735e720,352d0cf7f3e9be14dad7df644ad65efc27605ae2,m,NaN,NaN,NaN,4

In [6]:
#Basic Data Cleaning
df.drop(columns=['Unnamed: 0'])
df

,Unnamed: 0,index,total_cup_points,species,owner,country_of_origin,farm_name,lot_number,mill,ico_number,...,category_two_defects,expiration,certification_body,certification_address,certification_contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters,length
0,0,0,90.58,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,...,0,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0,4
1,1,1,89.92,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,...,1,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0,4
2,2,3,89.00,Arabica,yidnekachew dabessa,Ethiopia,yidnekachew dabessa coffee plantation,NaN,wolensu,NaN,...,2,"March 25th, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1800.0,2200.0,2000.0,4
3,3,4,88.83,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,...,2,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0,4
4,4,5,88.83,Arabica,ji-ae ahn,Brazil,NaN,NaN,NaN,NaN,...,1,"September 3rd, 2014",Specialty Coffee Institute of Asia,726e4891cf2c9a4848768bd34b668124d12c4224,b70da261fcc84831e3e9620c30a8701540abc200,m,NaN,NaN,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1124,1124,1334,78.75,Robusta,luis robles,Ecuador,robustasa,Lavado 1,our own lab,NaN,...,1,"January 18th, 2017",Specialty Coffee Association,ff7c18ad303d4b603ac3f8cff7e611ffc735e720,352d0cf7f3e9be14dad7df644ad65efc27605ae2,m,NaN,NaN,NaN,4
1125,1125,1335,78.08,Robusta,luis robles,Ecuador,robustasa,Lavado 3,own laboratory,NaN,...,0,"January 18th, 2017",Specialty Coffee Association,ff7c18ad303d4b603ac3f8cff7e611ffc735e720,352d0cf7f3e9be14dad7df644ad65efc27605ae2,m,40.0,40.0,40.0,4
1126,1126,1336,77.17,Robusta,james moore,United States,fazenda cazengo,NaN,cafe cazengo,NaN,...,6,"December 23rd, 2015",Specialty Coffee Association,ff7c18ad303d4b603ac3f8cff7e611ffc735e720,352d0cf7f3e9be14dad7df644ad65efc27605ae2,m,795.0,795.0,795.0,4
1127,1127,1337,75.08,Robusta,cafe politico,India,NaN,NaN,NaN,14-1118-2014-0087,...,1,"August 25th, 2015",Specialty Coffee Association,ff7c18ad303d4b603ac3f8cff7e611ffc735e720,352d0cf7f3e9be14dad7df644ad65efc27605ae2,m,NaN,NaN,NaN,4
1128,1128,1338,73.75,Robusta,cafe politico,Vietnam,NaN,NaN,NaN,NaN,...,9,"August 25th, 2015",Specialty Coffee Association,ff7c18ad303d4b603ac3f8cff7e611ffc735e720,352d0cf7f3e9be14dad7df644ad65efc27605ae2,m,NaN,NaN,NaN,4